export default {
  name: 'domain',
  attributes: {
    name: '',
    identifier: '',
    hostname: '',
    color: '',
    sender_email: '',
    contact_email: '',
    support_email: '',
    business_contact: null,
    search_radius: [],
    search_radius_default: 0,
    title: '',
    lat: 0.0,
    lng: 0.0,
    facebook_app_id: '',
    facebook_verification_id: '',
    network_traffic: false,
    hide_result_count: false,
    use_extra_boost: false,
    use_demonstration_page: false,
    self_register_has_new_jobmanagement: false,
  },
};
